name: Pull Request Build

on:
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn
      - run: yarn test
          
      - name: Bump version
        run: |
          git reset --hard
          echo yarn version --prerelease --preid "pr$PR_ID.$BUILD_NUMBER" --no-git-tag-version
          yarn version --prerelease --preid "pr$PR_ID.$BUILD_NUMBER" --no-git-tag-version
          git status -vv
          yarn build
          git add . || true
          git commit -m "Bump prerelease version" || true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR_ID: ${{ github.event.number }}
          BUILD_NUMBER: ${{ github.run_number }}
          
      - name: npm publish
        run: |
          export PR_PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
          echo PR Package Version is: [$PR_PACKAGE_VERSION]
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish --tag "$PR_PACKAGE_VERSION"
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
